# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公告名称')),
                ('type', models.IntegerField(choices=[(0, '创新创业项目公告'), (1, '立项公告'), (2, '结题公告')], default=0, verbose_name='公告类型')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='公告描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动申报时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='截止申报时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='项目验收时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='公告发布时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='NoticeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(blank=True, null=True, upload_to='notices/%Y/%m', verbose_name='附件')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.Notice', verbose_name='公告')),
            ],
            options={
                'verbose_name': '公告附件',
                'verbose_name_plural': '公告附件',
            },
        ),
    ]
