# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('0', '创新创业项目公告'), ('1', '立项公告'), ('2', '结题公告')], default='0', max_length=2, verbose_name='公告类型'),
        ),
    ]
