# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20180522_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.IntegerField(choices=[(0, '创新创业项目公告'), (1, '立项公告'), (2, '结题公告')], default=0, verbose_name='公告类型'),
        ),
    ]
