# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0003_auto_20180522_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('m_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=7, verbose_name='性别')),
                ('m_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('m_major', models.CharField(max_length=10, verbose_name='专业')),
                ('m_grade', models.CharField(max_length=10, verbose_name='年级')),
                ('m_student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('m_college', models.IntegerField(choices=[(0, '电子信息学院'), (1, '机电工程学院'), (2, '计算机学院'), (3, '材料与食品学院'), (4, '人文社会科学学院'), (5, '管理学院'), (6, '经贸学院'), (7, '外国语学院'), (8, '艺术设计学院')], default=0, verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='课题名称')),
                ('p_type', models.IntegerField(choices=[(0, '创新训练'), (1, '创业训练'), (2, '创业实践')], verbose_name='课题类型')),
                ('p_application', models.FileField(upload_to='application/%Y/%m', verbose_name='项目申请书')),
                ('p_middle', models.FileField(blank=True, null=True, upload_to='middle/%Y/%m', verbose_name='中期报告')),
                ('p_status', models.IntegerField(choices=[(0, '待审核'), (1, '待评分'), (2, '待立项'), (3, '已立项'), (4, '中期检查'), (5, '中期检查通过'), (6, '已验收'), (7, '驳回重填'), (8, '延期审核中'), (9, '已延期'), (10, '终止')], default=0, verbose_name='项目状态')),
                ('p_desc', models.TextField(blank=True, null=True, verbose_name='项目简介')),
                ('p_comment', models.TextField(blank=True, null=True, verbose_name='初审意见')),
                ('p_level', models.IntegerField(choices=[(0, '未立项'), (1, '校级立项'), (2, '省级立项'), (3, '国家级立项')], default=0, verbose_name='立项级别')),
                ('p_code', models.IntegerField(blank=True, null=True, verbose_name='项目所属一级学科代码')),
                ('financial_appropriation', models.IntegerField(blank=True, null=True, verbose_name='财政拨款（元）')),
                ('college_appropriation', models.IntegerField(blank=True, null=True, verbose_name='学校拨款（元）')),
                ('d_name', models.CharField(max_length=20, verbose_name='负责人姓名')),
                ('d_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=7, verbose_name='负责人性别')),
                ('d_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='负责人联系电话')),
                ('d_qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人QQ')),
                ('d_major', models.CharField(max_length=10, verbose_name='负责人专业')),
                ('d_student_id', models.CharField(max_length=20, verbose_name='负责人学号')),
                ('d_college', models.IntegerField(choices=[(0, '电子信息学院'), (1, '机电工程学院'), (2, '计算机学院'), (3, '材料与食品学院'), (4, '人文社会科学学院'), (5, '管理学院'), (6, '经贸学院'), (7, '外国语学院'), (8, '艺术设计学院')], default=0, verbose_name='所属学院')),
                ('d_email', models.EmailField(max_length=50, verbose_name='负责人邮箱')),
                ('t_name', models.CharField(max_length=10, verbose_name='指导老师')),
                ('t_gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=7, verbose_name='指导老师性别')),
                ('t_nation', models.CharField(blank=True, max_length=10, null=True, verbose_name='指导老师民族')),
                ('t_birthday', models.DateField(blank=True, null=True, verbose_name='指导老师生日')),
                ('t_title', models.CharField(blank=True, max_length=10, null=True, verbose_name='专业/职称/职务')),
                ('t_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='指导老师联系电话')),
                ('t_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='指导老师邮箱')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='最后期限')),
                ('delay_result', models.TextField(blank=True, null=True, verbose_name='延期原因')),
                ('e_comment', models.TextField(blank=True, null=True, verbose_name='专家意见')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('expert_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ExpertGroup', verbose_name='项目所属专家组')),
                ('p_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
                ('p_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.Notice', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '学生课题',
                'verbose_name_plural': '学生课题',
                'ordering': ['p_status'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='专家')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='学生课题')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='所属项目'),
        ),
    ]
